coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

# Flag management for different packages
flag_management:
  individual_flags:
    - name: backend
      carryforward: true
    - name: frontend
      carryforward: true
    - name: publisher
      carryforward: true
    - name: shared
      carryforward: true

# Coverage status checks for each flag
coverage:
  status:
    project:
      backend:
        flags:
          - backend
        target: 30%
      frontend:
        flags:
          - frontend
        target: 30%
      publisher:
        flags:
          - publisher
        target: 30%
      shared:
        flags:
          - shared
        target: 30%

# Comment configuration
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  show_carryforward_flags: true
